version: '3'

services:
  shl-recommender:
    build: .
    ports:
      - "8000:8000" 
      - "7860:7860"  
    volumes:
      - ./app/data.csv:/app/data.csv
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
