version: '3'

services:
  shl-recommender:
    build: .
    ports:
      - "8000:8000"
      - "7860:7860"
    volumes:
      - ./data.csv:/app/data.csv
      - ./model_cache:/app/model_cache
    environment:
      - PYTHONUNBUFFERED=1
      - TRANSFORMERS_CACHE=/app/model_cache
      - HF_HOME=/app/model_cache
      - SENTENCE_TRANSFORMERS_HOME=/app/model_cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
